- name: task variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: course info 
    ansible.builtin.debug:
      msg: "Course is: {{ Course }}, Duration is: {{ Duration }}, Trainer is: {{ Trainer }}"   