- name: variables preference
  hosts: local
  connection: local
  # vars:
  #   Name: from play var
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: Name
  #   prompt: What is your Name?
  #   private: false
  tasks:
  - name: variables preference
    # vars:
    #   Name: from task var
    ansible.builtin.debug:
      msg: "{{ Name }}"

# 1.cmd or args
# 2.task 
# 3.files
# 4.prompt
# 5.play