- name: facts
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"